<footer class="main-footer">
    <div class="footer-left">
        <div class="col-12 rounded-top text-center" style="bottom: 0; font-weight: bold;padding: 10px;">
            Copyright &copy; {{ date('Y') }} | All Rights Reserved
        </div>
    </div>
    <div class="footer-right">
        <div class="col-12 rounded-top text-center" style="bottom: 0; font-weight: bold;padding: 10px;">
            Developed by <b><a href="https://www.w3asolution.com">W3aSolution</a></b>
        </div>
    </div>
</footer>
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> --}}

<!-- jQuery 3.4.1 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/assets/js/bootstrap.min.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<script src="{{ asset('assets') }}/js/app.min.js"></script>

<script src="{{ asset('/assets/js/main.js') }}"></script>
<script src="{{ asset('/assets/js/ajax_submit.js') }}"></script>
<script src="{{ asset('/assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('/assets/js/jquery.plainoverlay.min.js') }}"></script>


<script src="{{ asset('/assets/plugins/sweet-alert/sweetalert.min.js') }}"></script>

<script src="{{ asset('/assets/plugins/select2/select2.full.min.js') }}"></script>


<!-- Toastr  library -->
<script src="{{ asset('/assets/plugins/toastr/toastr.min.js') }}"></script>

<!-- icheck  library -->
<script src="{{ asset('/assets/plugins/iCheck/icheck.min.js') }}"></script>

<!-- Datepicker library -->
<script src="{{ asset('/assets/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('assets/js/jquery.printElement.min.js') }}"></script>
<script src="https://cdn.tiny.cloud/1/8ehi0we599ewjbxknn0a81zdjny356zz1f3mmpg0udti7b9b/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>

<script>
    $.fn.modal.Constructor.prototype.enforceFocus = function() {};
</script>
<script>
    function notify_view(type, message) {

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr[type](message);

    }
</script>

<!-- General JS Scripts -->
<!-- JS Libraies -->
<!-- Page Specific JS File -->
<script src="{{ asset('assets') }}/js/page/index.js"></script>

<!-- Template JS File -->
<script src="{{ asset('assets') }}/js/scripts.js"></script>
<!-- Custom JS File -->
<script src="{{ asset('assets') }}/js/custom.js"></script>
<script src="{{ asset('assets') }}/bundles/apexcharts/apexcharts.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
@foreach ($errors->all() as $error)
    <script>
        toastr.error('{{ $error }}')
    </script>
@endforeach
<script type="text/javascript">
    @if (Session::has('success'))
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }
        toastr.success("{{ session('success') }}");
    @endif
    @if (Session::has('error'))
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }
        toastr.error("{{ session('error') }}");
    @endif
    @if (Session::has('info'))
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }
        toastr.info("{{ session('info') }}");
    @endif
    @if (Session::has('warning'))
        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }
        toastr.warning("{{ session('warning') }}");
    @endif
</script>
{{-- bootstrap multiselect --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.1/js/bootstrap-multiselect.min.js">
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/js/bootstrap-select.min.js"></script>

<script>
    const districtsBn = {
        'Barguna': 'বরগুনা',
        'Amtali': 'আমতলী',
        'Bamna': 'বামনা',
        'Barguna Sadar': 'বরগুনা সদর',
        'Betagi': 'বেতাগী',
        'Patharghata': 'পাথরঘাটা',
        'Taltali': 'তালতলী',
        'Barishal': 'বরিশাল',
        'Agailjhara': 'আগৈলঝাড়া',
        'Babuganj': 'বাবুগঞ্জ',
        'Bakerganj': 'বাকেরগঞ্জ',
        'Banaripara': 'বানারীপাড়া',
        'Barishal Sadar': 'বরিশাল সদর',
        'Gaurnadi': 'গৌরনদী',
        'Hizla': 'হিজলা',
        'Mehendiganj': 'মেহেন্দিগঞ্জ',
        'Muladi': 'মুলাদী',
        'Wazirpur': 'উজিরপুর',
        'Bhola': 'ভোলা',
        'Bhola Sadar': 'ভোলা সদর',
        'Burhanuddin': 'বোরহানউদ্দিন',
        'Char Fasson': 'চরফ্যাশন',
        'Daulatkhan': 'দৌলতখান',
        'Lalmohan': 'লালমোহন',
        'Manpura': 'মনপুরা',
        'Tazumuddin': 'তাজুমদ্দিন',
        'Jhalokati': 'ঝালকাঠি',
        'Jhalokati Sadar': 'ঝালকাঠি সদর',
        'Kathalia': 'কাঁঠালিয়া',
        'Nalchity': 'নলছিটি',
        'Rajapur': 'রাজাপুর',
        'Patuakhali': 'পটুয়াখালী',
        'Bauphal': 'বাউফল',
        'Dashmina': 'দশমিনা',
        'Dumki': 'দুমকি',
        'Galachipa': 'গলাচিপা',
        'Kalapara': 'কলাপাড়া',
        'Mirzaganj': 'মির্জাগঞ্জ',
        'Patuakhali Sadar': 'পটুয়াখালী সদর',
        'Rangabali': 'রাঙ্গাবালী',
        'Pirojpur': 'পিরোজপুর',
        'Bhandaria': 'ভাণ্ডারিয়া',
        'Kawkhali': 'কাউখালী (পিরোজপুর)',
        'Mathbaria': 'মঠবাড়ীয়া',
        'Nazirpur': 'নাজিরপুর',
        'Zianagar': 'জিয়ানগর',
        'Nesarabad (Swarupkati)': 'নেছারাবাদ (স্বরূপকাঠী)',
        'Pirojpur Sadar': 'পিরোজপুর সদর',
        'Bandarban': 'বান্দরবান',
        'Bandarban Sadar': 'বান্দরবান সদর',
        'Lama': 'লামা',
        'Naikhongchhari': 'নাইক্ষ্যংছড়ি',
        'Rowangchhari': 'রোয়াংছড়ি',
        'Ruma': 'রুমা',
        'Thanchi': 'থানচি',
        'Ali Kadam': 'আলিকদম',
        'Brahmanbaria': 'ব্রাহ্মণবাড়িয়া',
        'Ashuganj': 'আশুগঞ্জ',
        'Akhaura': 'আখাউড়া',
        'Bancharampur': 'বাঞ্ছারামপুর',
        'Brahmanbaria Sadar': 'ব্রাহ্মণবাড়িয়া সদর',
        'Kasba': 'কসবা',
        'Nabinagar': 'নবীনগর',
        'Nasirnagar': 'নাসিরনগর',
        'Sarail': 'সরাইল',
        'Chandpur': 'চাঁদপুর',
        'Chandpur Sadar': 'চাঁদপুর সদর',
        'Faridganj': 'ফরিদগঞ্জ',
        'Shahrasti': 'শাহরাস্তি',
        'Haimchar': 'হাইমচর',
        'Haziganj': 'হাজীগঞ্জ',
        'Kachua': 'কচুয়া',
        'Matlab Dakkhin': 'মতলব দক্ষিণ',
        'Matlab Uttar': 'মতলব উত্তর',
        'Chattogram': 'চট্টগ্রাম',
        'Anwara': 'আনোয়ারা',
        'Banshkhali': 'বাঁশখালী',
        'Boalkhali': 'বোয়ালখালী',
        'Chandanaish': 'চন্দনাইশ',
        'Chattogram Sadar': 'চট্টগ্রাম সদর',
        'Fatikchhari': 'ফটিকছড়ি',
        'Hathazari': 'হাটহাজারী',
        'Lohagara': 'লোহাগাড়া',
        'Mirsharai': 'মীরসরাই',
        'Patiya': 'পটিয়া',
        'Rangunia': 'রাঙ্গুনিয়া',
        'Raozan': 'রাউজান',
        'Sandwip': 'সন্দ্বীপ',
        'Satkania': 'সাতকানিয়া',
        'Sitakunda': 'সীতাকুণ্ড',
        'Cumilla': 'কুমিল্লা',
        'Barura': 'বড়ুরা',
        'Brahmanpara': 'ব্রাহ্মণপাড়া',
        'Burichang': 'বুড়িচং',
        'Chandina': 'চান্দিনা',
        'Chauddagram': 'চৌদ্দগ্রাম',
        'Cumilla Adarsha Sadar': 'কুমিল্লা আদর্শ সদর',
        'Cumilla Sadar Dakshin': 'কুমিল্লা সদর দক্ষিণ',
        'Daudkandi': 'দাউদকান্দি',
        'Debidwar': 'দেবীদ্বার',
        'Homna': 'হোমনা',
        'Laksam': 'লাকসাম',
        'Meghna': 'মেঘনা',
        'Monohorgonj': 'মনোহরগঞ্জ',
        'Muradnagar': 'মুরাদনগর',
        'Nangalkot': 'নাঙ্গলকোট',
        'Titas': 'তিতাস',
        'Cox\'s Bazar': 'কক্সবাজার',
        'Chakaria': 'চকরিয়া',
        'Cox\'s Bazar Sadar': 'কক্সবাজার সদর',
        'Kutubdia': 'কুতুবদিয়া',
        'Maheshkhali': 'মহেশখালী',
        'Pekua': 'পেকুয়া',
        'Ramu': 'রামু',
        'Ukhia': 'উখিয়া',
        'Teknaf': 'টেকনাফ',
        'Feni': 'ফেনী',
        'Chhagalnaiya': 'ছাগলনাইয়া',
        'Daganbhuiyan': 'দাগনভূঞা',
        'Feni Sadar': 'ফেনী সদর',
        'Parshuram': 'পরশুরাম',
        'Sonagazi': 'সোনাগাজী',
        'Fulgazi': 'ফুলগাজী',
        'Khagrachari': 'খাগড়াছড়ি',
        'Dighinala': 'দীঘিনালা',
        'Khagrachari Sadar': 'খাগড়াছড়ি সদর',
        'Lakshmichhari': 'লক্ষ্মীছড়ি',
        'Mahalchhari': 'মহালছড়ি',
        'Manikchhari': 'মানিকছড়ি',
        'Matiranga': 'মাটিরাঙ্গা',
        'Panchhari': 'পানছড়ি',
        'Ramgarh': 'রামগড়',
        'Lakshmipur': 'লক্ষ্মীপুর',
        'Lakshmipur Sadar': 'লক্ষ্মীপুর সদর',
        'Raipur': 'রায়পুর',
        'Ramganj': 'রামগঞ্জ',
        'Ramgati': 'রামগতি',
        'Kamalnagar': 'কমলনগর',
        'Noakhali': 'নোয়াখালী',
        'Begumganj': 'বেগমগঞ্জ',
        'Chatkhil': 'চাটখিল',
        'Companiganj': 'কোম্পানীগঞ্জ',
        'Hatiya': 'হাতিয়া',
        'Kabirhat': 'কবিরহাট',
        'Noakhali Sadar': 'নোয়াখালী সদর',
        'Senbagh': 'সেনবাগ',
        'Subarnachar': 'সুবর্ণচর',
        'Rangamati': 'রাঙ্গামাটি',
        'Baghaichhari': 'বাঘাইছড়ি',
        'Barkal': 'বরকল',
        'Kaptai': 'কাপ্তাই',
        'Juraichhari': 'জুরাছড়ি',
        'Rajasthali': 'রাজস্থলী',
        'Belaichhari': 'বিলাইছড়ি',
        'Langadu': 'লংগদু',
        'Naniarchar': 'নানিয়ারচর',
        'Rangamati Sadar': 'রাঙ্গামাটি সদর',
        'Barisal': 'বরিশাল',
        'Chittagong': 'চট্টগ্রাম',
        'Dhaka': 'ঢাকা',
        'Khulna': 'খুলনা',
        'Mymensingh': 'ময়মনসিংহ',
        'Rajshahi': 'রাজশাহী',
        'Rangpur': 'রংপুর',
        'Sylhet': 'সিলেট',
        'Adabor': 'আদাবর',
        'Badda': 'বাড্ডা',
        'Bangsal': 'বংশাল',
        'Cantonment': 'ক্যান্টনমেন্ট',
        'Chawkbazar': 'চৌকিবাজার',
        'Dhanmondi': 'ধানমন্ডি',
        'Gendaria': 'গেন্ডারিয়া',
        'Gulshan': 'গুলশান',
        'Hazaribagh': 'হাজারীবাগ',
        'Jatrabari': 'যাত্রাবাড়ি',
        'Kadamtali': 'কদমতলী',
        'Kafrul': 'কাফরুল',
        'Kalabagan': 'কালাবাগান',
        'Kamrangirchar': 'কমরাঙ্গীরচর',
        'Khilkhet': 'খিলক্ষেত',
        'Khilgaon': 'খিলগাঁও',
        'Kotwali': 'কোতয়ালি',
        'Lalbagh': 'লালবাগ',
        'Mirpur': 'মিরপুর',
        'Mohammadpur': 'মোহাম্মদপুর',
        'Motijheel': 'মোটিজিল',
        'New Market': 'নিউ মার্কেট',
        'Pallabi': 'পল্লবী',
        'Paltan': 'পল্টন',
        'Ramna': 'রমনা',
        'Rampura': 'রামপুরা',
        'Sabujbagh': 'সবুজবাগ',
        'Shah Ali': 'শাহ আলী',
        'Shahbagh': 'শাহবাগ',
        'Shyampur': 'শিয়ালদহ',
        'Sutrapur': 'সূত্রাপুর',
        'Tejgaon': 'তেজগাঁও',
        'Uttar Khan': 'উত্তর খান',
        'Uttara': 'উত্তরা',
        'Vatara': 'ভাটারা',

        'Faridpur': 'ফরিদপুর',
        'Alfadanga': 'আলফাডাঙ্গা',
        'Bhanga': 'ভাঙ্গা',
        'Boalmari': 'বোয়ালমারী',
        'Charbhadrasan': 'চরভদ্রাসন',
        'Faridpur Sadar': 'ফরিদপুর সদর',
        'Madhukhali': 'মধুখালী',
        'Nagarkanda': 'নগরকান্দা',
        'Sadarpur': 'সদরপুর',
        'Saltha': 'সালথা',
        'Gazipur': 'গাজীপুর',
        'Gazipur Sadar': 'গাজীপুর সদর',
        'Kaliakair': 'কালিয়াকৈর',
        'Kaliganj': 'কালীগঞ্জ',
        'Kapasia': 'কাপাসিয়া',
        'Sreepur': 'শ্রীপুর',
        'Gopalganj': 'গোপালগঞ্জ',
        'Gopalganj Sadar': 'গোপালগঞ্জ সদর',
        'Kashiani': 'কাশিয়ানি',
        'Kotalipara': 'কোটালীপাড়া',
        'Muksudpur': 'মুকসুদপুর',
        'Tungipara': 'তুঙ্গিপাড়া',
        'Kishoreganj': 'কিশোরগঞ্জ',
        'Austagram': 'আউশকান্দি',
        'Bajitpur': 'বাজিতপুর',
        'Bhairab': 'ভৈরব',
        'Hossainpur': 'হোসেনপুর',
        'Itna': 'ইটনা',
        'Karimganj': 'কারিমগঞ্জ',
        'Katiadi': 'কাটিয়াদি',
        'Kishoreganj Sadar': 'কিশোরগঞ্জ সদর',
        'Kuliarchar': 'কুলিয়ারচর',
        'Mithamain': 'মিঠামইন',
        'Nikli': 'নিকলী',
        'Pakundia': 'পাকুন্দিয়া',
        'Tarail': 'তারাইল',
        'Madaripur': 'মাদারীপুর',
        'Kalkini': 'কালকিনি',
        'Madaripur Sadar': 'মাদারীপুর সদর',
        'Rajoir': 'রাজৈর',
        'Shibchar': 'শিবচর',
        'Manikganj': 'মানিকগঞ্জ',
        'Daulatpur': 'দৌলতপুর',
        'Ghior': 'ঘিওর',
        'Harirampur': 'হরিরামপুর',
        'Manikganj Sadar': 'মানিকগঞ্জ সদর',
        'Saturia': 'সাতুরিয়া',
        'Shibalaya': 'শিবালয়',
        'Singair': 'সিংগাইর',
        'Munshiganj': 'মুন্সিগঞ্জ',
        'Gazaria': 'গজারিয়া',
        'Lohajang': 'লহজাং',
        'Munshiganj Sadar': 'মুন্সিগঞ্জ সদর',
        'Sirajdikhan': 'সিরাজদিখান',
        'Sreenagar': 'শ্রীনগর',
        'Tongibari': 'টঙ্গীবাড়ি',
        'Narayanganj': 'নারায়ণগঞ্জ',
        'Araihazar': 'আড়াইহাজার',
        'Bandar': 'বান্দর',
        'Narayanganj Sadar': 'নারায়ণগঞ্জ সদর',
        'Rupganj': 'রূপগঞ্জ',
        'Sonargaon': 'সোনারগাঁও',
        'Narsingdi': 'নরসিংদী',
        'Belabo': 'বেলাবো',
        'Monohardi': 'মোনহারী',
        'Narsingdi Sadar': 'নরসিংদী সদর',
        'Palash': 'পালাশ',
        'Raipura': 'রায়পুরা',
        'Shibpur': 'শিবপুর',
        'Rajbari': 'রাজবাড়ী',
        'Baliakandi': 'বালিয়াকান্দি',
        'Goalanda': 'গোলন্দা',
        'Pangsha': 'পাংশা',
        'Rajbari Sadar': 'রাজবাড়ী সদর',
        'Shariatpur': 'শরিয়তপুর',
        'Bhedarganj': 'ভেদরগঞ্জ',
        'Damudya': 'দামুদ্যা',
        'Gosairhat': 'গোসাইরহাট',
        'Naria': 'নড়িয়া',
        'Shariatpur Sadar': 'শরিয়তপুর সদর',
        'Zanjira': 'জঞ্জিরা',
        'Tangail': 'টাঙ্গাইল',
        'Basail': 'বাসাইল',
        'Bhuapur': 'ভূয়াপুর',
        'Delduar': 'দেলদুয়ার',
        'Dhanbari': 'ধানবাড়ি',
        'Ghatail': 'ঘাটাইল',
        'Gopalpur': 'গোপালপুর',
        'Kalihati': 'কালিহাতি',
        'Madhupur': 'মধুপুর',
        'Mirzapur': 'মির্জাপুর',
        'Nagarpur': 'নাগরপুর',
        'Sakhipur': 'সখীপুর',
        'Tangail Sadar': 'টাঙ্গাইল সদর',
        'Bagerhat': 'বাগেরহাট',
        'Bagerhat Sadar': 'বাগেরহাট সদর',
        'Chitalmari': 'চিতলমারী',
        'Fakirhat': 'ফকিরহাট',
        'Mollahat': 'মোল্লাহাট',
        'Mongla': 'মোংলা',
        'Morrelganj': 'মোরেলগঞ্জ',
        'Rampal': 'রামপাল',
        'Sarankhola': 'সারণখোলা',
        'Chuadanga': 'চুয়াডাঙ্গা',
        'Chuadanga Sadar': 'চুয়াডাঙ্গা সদর',
        'Alamdanga': 'আলমডাঙ্গা',
        'Damurhuda': 'দামুরহুদা',
        'Jibannagar': 'জীবননগর',
        'Jessore': 'যশোর',
        'Jessore Sadar': 'যশোর সদর',
        'Abhaynagar': 'অভয়নগর',
        'Bagherpara': 'বাঘেরপাড়া',
        'Chaugachha': 'চৌগাছা',
        'Jhikargachha': 'ঝিকরগাছা',
        'Keshabpur': 'কেশবপুর',
        'Manirampur': 'মনিরামপুর',
        'Sharsha': 'শার্শা',
        'Jhenaidah': 'ঝিনাইদহ',
        'Jhenaidah Sadar': 'ঝিনাইদহ সদর',
        'Harinakunda': 'হারিনাকুন্ডা',
        'Kotchandpur': 'কোটচাঁদপুর',
        'Maheshpur': 'মহেশপুর',
        'Shailkupa': 'শৈলকুপা',
        'Khulna': 'খুলনা',
        'Dacope': 'ডাকোপ',
        'Batiaghata': 'বাটিয়াঘাটা',
        'Dumuria': 'দুমুরিয়া',
        'Dighalia': 'দিঘলিয়া',
        'Koyra': 'কয়রা',
        'Paikgachha': 'পাইকগাছা',
        'Phultala': 'ফুলতলা',
        'Rupsa': 'রূপসা',
        'Terokhada': 'তেরখাদা',
        'Kushtia': 'কুষ্টিয়া',
        'Kushtia Sadar': 'কুষ্টিয়া সদর',
        'Bheramara': 'ভেরামারা',
        'Khoksa': 'খোকসা',
        'Kumarkhali': 'কুমারখালী',
        'Magura': 'মাগুরা',
        'Magura Sadar': 'মাগুরা সদর',
        'Shalikha': 'শালিখা',
        'Meherpur': 'মেহেরপুর',
        'Meherpur Sadar': 'মেহেরপুর সদর',
        'Gangni': 'গাংনী',
        'Mujibnagar': 'মুজিবনগর',
        'Narail': 'নড়াইল',
        'Narail Sadar': 'নড়াইল সদর',
        'Kalia': 'কালিয়া',
        'Satkhira': 'সাতক্ষীরা',
        'Satkhira Sadar': 'সাতক্ষীরা সদর',
        'Assasuni': 'আশাশুনি',
        'Debhata': 'দেবহাটা',
        'Kalaroa': 'কালরোয়া',
        'Shyamnagar': 'শ্যামনগর',
        'Tala': 'তালা',
        'Jamalkandi': 'জামালকান্দি',
        'Jamalkandi Sadar': 'জামালকান্দি সদর',
        'Bhaluka': 'ভালুকা',
        'Gafargaon': 'গফরগাঁও',
        'Haluaghat': 'হালুয়াঘাট',
        'Nandail': 'নন্দাইল',
        'Netrakona': 'নেত্রকোনা',
        'Jamalpur': 'জামালপুর',
        'Jamalpur Sadar': 'জামালপুর সদর',
        'Sarishabari': 'সরিষাবাড়ী',
        'Melandah': 'মেলান্দহ',
        'Dewanganj': 'দেওয়াঙ্গঞ্জ',
        'Islampur': 'ইসলামপুর',
        'Baksiganj': 'বাকসীগঞ্জ',
        'Mymensingh': 'ময়মনসিংহ',
        'Mymensingh Sadar': 'ময়মনসিংহ সদর',
        'Netrokona': 'নেত্রকোনা',
        'Netrokona Sadar': 'নেত্রকোনা সদর',
        'Atpara': 'আটপাড়া',
        'Barhatta': 'বারহাট্টা',
        'Durgapur': 'দুর্গাপুর',
        'Khaliajuri': 'খালিয়াজুরী',
        'Modon': 'মোডন',
        'Purbadhala': 'পূর্বধলা',
        'Shahid Moksud': 'শহীদ মোহসীন',
        'Sherpur': 'শেরপুর',
        'Sherpur Sadar': 'শেরপুর সদর',
        'Nalitabari': 'নালিতাবাড়ী',
        'Jhenaigati': 'ঝিনাইগাতি',
        'Sreebardi': 'শ্রীবাড়ী',
        'Nakla': 'নাকলা',
        'Bagura': 'বগুড়া',
        'Bagura Sadar': 'বগুড়া সদর',
        'Bogra': 'বগুড়া',
        'Bogra Sadar': 'বগুড়া সদর',
        'Dupchanchia': 'দুপচাঁচিয়া',
        'Dhunat': 'ধুনট',
        'Shajahanpur': 'শাজাহানপুর',
        'Sadar': 'সদর',
        'Kahalu': 'কাহালু',
        'Nandigram': 'নন্দিগ্রাম',
        'Pundro': 'পুন্দ্র',
        'Joypurhat': 'জয়পুরহাট',
        'Joypurhat Sadar': 'জয়পুরহাট সদর',
        'Kalai': 'কালাই',
        'Khetlal': 'খেতলাল',
        'Akandabari': 'আকন্দাবাড়ী',
        'Naogaon': 'নওগাঁ',
        'Naogaon Sadar': 'নওগাঁ সদর',
        'Atrai': 'আত্রাই',
        'Badalgachhi': 'বদলগাছী',
        'Dhamuirhat': 'ধামুইরহাট',
        'Mohadevpur': 'মহাদেবপুর',
        'Porsha': 'পোরশা',
        'Raninagar': 'রানীনগর',
        'Sapahar': 'সাপাহার',
        'Subarnapur': 'সুবর্ণপুর',
        'Natore': 'নাটোর',
        'Natore Sadar': 'নাটোর সদর',
        'Baraigram': 'বড়াইগ্রাম',
        'Bagatipara': 'বাগাতিপাড়া',
        'Gurudaspur': 'গুরুদাসপুর',
        'Lalpur': 'লালপুর',
        'Singra': 'সিংড়া',
        'Pabna': 'পাবনা',
        'Pabna Sadar': 'পাবনা সদর',
        'Bera': 'বেরার',
        'Chatmohar': 'চাটমোহর',
        'Ishwardi': 'ইশ্বরদী',
        'Sujanagar': 'সুজানগর',
        'Rajshahi': 'রাজশাহী',
        'Rajshahi Sadar': 'রাজশাহী সদর',
        'Bagha': 'বাঘা',
        'Charghat': 'চারঘাট',
        'Durgapur': 'দুর্গাপুর',
        'Puthia': 'পুঠিয়া',
        'Tanore': 'তানোর',
        'Sherpur': 'শেরপুর',
        'Sherpur Sadar': 'শেরপুর সদর',
        'Nakur': 'নাকুর',
        'Bogura': 'বগুড়া',
        'Bogura Sadar': 'বগুড়া সদর',
        'Dhunat': 'ধুনট',
        'Gabtali': 'গাবতলী',
        'Kahaloo': 'কাহালু',
        'Nandigram': 'নন্দিগ্রাম',
        'Sadar': 'সদর',
        'Shibganj': 'শিবগঞ্জ',
        'Sonatala': 'সোনাতলা',
        'Dinajpur': 'দিনাজপুর',
        'Birampur': 'বিরামপুর',
        'Chirirbandar': 'চিরিরবন্দর',
        'Dinajpur Sadar': 'দিনাজপুর সদর',
        'Ghoraghat': 'ঘোড়াঘাট',
        'Hakimpur': 'হাকিমপুর',
        'Kaharol': 'কাহারোল',
        'Nawabganj': 'নবাবগঞ্জ',
        'Parbatipur': 'পার্বতীপুর',
        'Sujanagar': 'সুজানগর',
        'Gaibandha': 'গাইবান্ধা',
        'Gaibandha Sadar': 'গাইবান্ধা সদর',
        'Gobindaganj': 'গোবিন্দগঞ্জ',
        'Palashbari': 'পালাশবাড়ী',
        'Sundarganj': 'সুন্দরগঞ্জ',
        'Shaghata': 'শাঘাটা',
        'Sadullapur': 'সাদুল্লাপুর',
        'Kurigram': 'কুড়িগ্রাম',
        'Bhurungamari': 'ভুরুঙ্গামারী',
        'Chilmari': 'চিলমারী',
        'Kurigram Sadar': 'কুড়িগ্রাম সদর',
        'Nageshwari': 'নাগেশ্বরী',
        'Rajarhat': 'রাজারহাট',
        'Rowmari': 'রৌমারী',
        'Ujirpur': 'উজিরপুর',
        'Lalmonirhat': 'লালমনিরহাট',
        'Aditmari': 'আদিতমারী',
        'Lalmonirhat Sadar': 'লালমনিরহাট সদর',
        'Hatibandha': 'হাতিবন্দা',
        'Patgram': 'পতগ্রাম',
        'Nilphamari': 'নীলফামারী',
        'Domar': 'ডোমার',
        'Nilphamari Sadar': 'নীলফামারী সদর',
        'Jaldhaka': 'জলঢাকা',
        'Saidpur': 'সৈদপুর',
        'Panchagarh': 'পঞ্চগড়',
        'Boda': 'বোদা',
        'Debiganj': 'দেবিগঞ্জ',
        'Panchagarh Sadar': 'পঞ্চগড় সদর',
        'Tetulia': 'তেতুলিয়া',
        'Rangpur': 'রংপুর',
        'Rangpur Sadar': 'রংপুর সদর',
        'Kawshalyganj': 'কাউশল্যগঞ্জ',
        'Mithapukur': 'মিঠাপুকুর',
        'Pirganj': 'পীরগঞ্জ',
        'Taraganj': 'তারাগঞ্জ',
        'Thakurgaon': 'ঠাকুরগাঁও',
        'Thakurgaon Sadar': 'ঠাকুরগাঁও সদর',
        'Baliadangi': 'বালিয়াডাঙ্গী',
        'Haripur': 'হরিপুর',
        'Pirgachha': 'পীরগাছা',
        'Ranishwar': 'রাণিশোড়',
        'Habiganj': 'হবিগঞ্জ',
        'Baniachong': 'বানিয়াচং',
        'Habiganj Sadar': 'হবিগঞ্জ সদর',
        'Lakhai': 'লাখাই',
        'Madhabpur': 'মাধবপুর',
        'Nabiganj': 'নবীগঞ্জ',
        'Shaistaganj': 'শায়েস্তাগঞ্জ',
        'Moulvibazar': 'মৌলভীবাজার',
        'Barlekha': 'বারলেখা',
        'Juri': 'জুরী',
        'Moulvibazar Sadar': 'মৌলভীবাজার সদর',
        'Rajnagar': 'রাজনগর',
        'Sreemangal': 'শ্রীমঙ্গল',
        'Kamalganj': 'কামালগঞ্জ',
        'Kulaura': 'কুলাউড়া',
        'Shreemangal': 'শ্রীমঙ্গল',
        'Sunamganj': 'সুনামগঞ্জ',
        'Bishwambharpur': 'বিশ্বম্ভরপুর',
        'Derai': 'দিরাই',
        'Dowarabazar': 'দোয়ারাবাজার',
        'Golarha': 'গোলারহ',
        'Jamalkandi': 'জামালকান্দি',
        'Jatrapur': 'জাত্রাপুর',
        'Sunamganj Sadar': 'সুনামগঞ্জ সদর',
        'Tahirpur': 'তাহিরপুর',
        // Sylhet Districts
        'Beanibazar': 'বিয়ানীবাজার',
        'Biswanath': 'বিশ্বনাথ',
        'Dakshin Surma': 'দক্ষিণ সুরমা',
        'Gowainghat': 'গোয়াইনঘাট',
        'Jaintiapur': 'জৈন্তিয়াপুর',
        'Osmani Nagar': 'ওসমানীনগর',
        'Sadar': 'সদর',
        'South Surma': 'দক্ষিণ সুরমা',
        'Utrara': 'উত্ররা',
    }
    const isEnglish = {{ App::getLocale() == 'en' ? 'true' : 'false' }};
</script>
